name: bootcamp assignment

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installing node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  
      - name: installing surge
        run: npm install --golobal surge
      - name: deploying  on surge
        run: surge ./ asadsarazai.surge.sh --token ${{ secrets.surge_token}}
docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
